# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function to perform EBMA using Rcpp
#'
#' @param x Numeric Matrix of x values
#' @param y Numeric Vector of actual values
#' @param weights Numeric Vector of weights for each model
#' @param sd Standard Deviation
#' @param tolerance Specified tolerance level 
#'
#' @export
NULL

ebma <- function(x, y, weights, sd, tolerance) {
    .Call(`_ebma_ebma`, x, y, weights, sd, tolerance)
}

#' Get weighted values using Rcpp
#'
#' @param z Numeric Matrix of z values
NULL

#'
#' @export
NULL

w_hat <- function(z) {
    .Call(`_ebma_w_hat`, z)
}

#' Get z hat values using Rcpp
#'
#' @param x Numeric Matrix of x values
#' @param y Numeric Vector of actual values
#' @param weights Numeric Vector of weights for each model
#' @param sd Standard Deviation
#'
#' @export
NULL

z_hat <- function(x, y, weights, sd) {
    .Call(`_ebma_z_hat`, x, y, weights, sd)
}

