# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ebma <- function(x, y, weights, sd, tolerance) {
    .Call(`_ebma_ebma`, x, y, weights, sd, tolerance)
}

w_hat <- function(z) {
    .Call(`_ebma_w_hat`, z)
}

z_hat <- function(x, y, weights, sd) {
    .Call(`_ebma_z_hat`, x, y, weights, sd)
}

